# Site settings
title: Data Salience
name: Data Salience
header-img: img/home-bg.jpg
email: me@gregvi.al
description: "This blogs is all about Data Science!"
baseurl: ""
url: "https://gregvial.github.io"
#twitter_username: SBootstrap
github_username:  GregVial
#facebook_username:  StartBootstrap
linkedin_username: in/gregoryvial
email_username:  me@gregvi.al

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
